#!/bin/bash



#####Add Manjaro bashrc#####
mv -v bashrc ~/.bashrc
tput setaf 2
echo -e "\033[5m Manjaro Bashrc Added"
tput sgr0



#####Edit pacman.conf#####
#COMMENT /s/^.// replaces character 1 "." with what's within the //, so it deletes it
sudo sed -i '/#Color/s/^.//' /etc/pacman.conf
sudo sed -i '/#VerbosePkgLists/s/^.//' /etc/pacman.conf
#COMMENT /s/\n/\n#/ replaces \n(ext line) with \n(ext something else)
sudo sed -i '/#ParallelDownloads = 5/!b;N;s/^.//;s/\n/\nILoveCandy/' /etc/pacman.conf
#COMMENT /s/^/#/ replaces character 0 with what's within the //, so it adds # to the beginning of the line
sudo sed -i '/\[multilib-testing\]/!b;N;s/^/#/;s/\n/\n#/' /etc/pacman.conf
sudo sed -i '/##\[multilib-testing\]/!b;N;s/^.//;s/\n##/\n#/' /etc/pacman.conf
tput setaf 2
echo -e "\033[5m Pacman Config Set"
tput sgr0



#####Install CPU microcode#####
echo what cpu?
read cpu

if [ "$cpu" == "amd" ]

	then
	
		tput sgr0
		sudo pacman -S amd-ucode --noconfirm --needed
		tput setaf 2
		echo -e "\033[5m ${cpu} CPU microcode has been installed"
		tput sgr0
	
	elif [ "$cpu" == "intel" ]; then
	
		sudo pacman -S intel-ucode --noconfirm --needed
		tput setaf 2
		echo -e "\033[5m ${cpu} CPU microcode has been installed"
		tput sgr0
		
	else
	
		tput setaf 1
		echo -e "\033[5m CPU microcode has been NOT installed"
		tput sgr0
	
fi



#####Install GPU driver#####
echo what gpu?
read gpu

if [ "$gpu" == "amd" ]

	then
	
		sudo pacman -S mesa lib32-mesa vulkan-radeon lib32-vulkan-radeon libva-mesa-driver lib32-libva-mesa-driver mesa-vdpau lib32-mesa-vdpau libva-vdpau-driver lib32-libva-vdpau-driver libvdpau-va-gl --noconfirm --needed
		tput setaf 2
		echo -e "\033[5m ${gpu} GPU driver has been installed"
		tput sgr0
		
	else
	
		tput setaf 1
		echo -e "\033[5m GPU driver has been NOT installed"
		tput sgr0
fi



#####Uniformize GTK & QT look#####
QTSTYLE=(grep QT_STYLE_OVERRIDE /etc/environment)

if [ "QTSTYLE" != "QT_STYLE_OVERRIDE=kvantum" ]

	then
	
		sudo awk 'BEGIN{printf "\nQT_STYLE_OVERRIDE=kvantum" >> "/etc/environment"}'
		tput setaf 2
		echo -e "\033[5m GTK and QT Style Override Set"
		tput sgr0
	
fi



#####Add fcitx variables#####
GTK=(grep GTK_IM_MODULE /etc/environment)
QTMOD=(grep QT_IM_MODULE /etc/environment)
XMOD=(grep XMODIFIERS=@im /etc/environment)
    
if [ "GTK" != "GTK_IM_MODULE=fcitx" ]

	then
	
		sudo awk 'BEGIN{printf "\nGTK_IM_MODULE=fcitx" >> "/etc/environment"}'

fi

if [ "QTMOD" != "QT_IM_MODULE=fcitx" ]

	then
	
		sudo awk 'BEGIN{printf "\nQT_IM_MODULE=fcitx" >> "/etc/environment"}'
		
fi

if [ "XMOD" != "XMODIFIERS=@im=fcitx=fcitx" ]

	then
	
		sudo awk 'BEGIN{printf "\nXMODIFIERS=@im=fcitx" >> "/etc/environment"}'
		tput setaf 2
		echo -e "\033[5m Fcitx Is Now Set"
		tput sgr0

fi



#####Update grub settings#####
sudo sed -i 's/5/1/' /etc/default/grub
sudo sed -i 's/ quiet//' /etc/default/grub
sudo sed -i '/#GRUB_TERMINAL_OUTPUT/s/^.//' /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg
tput setaf 2
echo -e "\033[5m Grub Settings Updated"
tput sgr0



#####Add fixkeys#####
chmod +x fixkeys
sudo mv fixkeys /usr/local/bin/
tput setaf 2
echo -e "\033[5m Fix Keys Script Added"
tput sgr0



#####Uninstall programs#####
func_install()
{
	if pacman -Qi $1 &> /dev/null

		then
		
			tput sgr0
			sudo pacman -Rn --noconfirm $1
			echo "Uninstalling package" $1

		else
		
			tput sgr0
			tput setaf 4
			echo ""$1" is not installed"

	fi
}

list=(
		htop
		parole
		ristretto
		vim
		vim-runtime
		xarchiver
		xfburn
		xfce4-sensors-plugin
		xfce4-taskmanager
	)

count=0

for name in "${list[@]}"

	do
	
		count=$[count+1]
		tput setaf 3
		echo -e "\033[7m Uninstalling "$count":"$name;
		func_install $name
		
	done

tput setaf 2
echo -e "\033[5m Software has been uninstalled"
tput sgr0



#####Install programs#####
func_install()
{
	if pacman -Qi $1 &> /dev/null

		then
		
			tput sgr0
			tput setaf 4
			echo ""$1" is installed"

		else
		
			tput sgr0
			sudo pacman -S --noconfirm --needed $1
			echo "Installing package" $1

	fi
}

list=(
		archlinux-wallpaper
		arc-gtk-theme
		btop
		capitaine-cursors
		evince
		fcitx5
		fcitx5-configtool
		fcitx5-gtk
		fcitx5-mozc
		fcitx5-qt
		ffmpeg
		file-roller
		git
		gnome-calculator
		gnome-disk-utility
		gnome-font-viewer
		grub-btrfs
		gtk4
		gvfs-mtp
		kvantum
		libreoffice-fresh
		linux-headers
		lxtask
		mediainfo
		mesa-vdpau
		mpv
		ntfs-3g
		p7zip
		papirus-icon-theme
		qbittorrent
		reflector
		ttf-ubuntu-font-family
		vdpauinfo
		viewnior
		yt-dlp
		zip
	)

count=0

for name in "${list[@]}"

	do
		count=$[count+1]
		tput setaf 3
		echo -e "\033[7m Installing "$count":"$name;
		func_install $name
		
	done

tput setaf 2
echo -e "\033[5m Software has been installed"
tput sgr0



#####Enable LightDM autologin######
sudo groupadd -r autologin
sudo gpasswd -a $USER autologin
sudo sed -i "s/#autologin-user=/autologin-user=$USER/" /etc/lightdm/lightdm.conf
tput setaf 2
echo -e "\033[5m LightDM Set To Autologin"
tput sgr0



#####Customize LightDM#####
sudo sed -i 's/#background=/background=\/usr\/share\/backgrounds\/archlinux\/awesome.png/' /etc/lightdm/lightdm-gtk-greeter.conf
sudo sed -i 's/#theme-name=/theme-name=Arc-Dark/' /etc/lightdm/lightdm-gtk-greeter.conf
sudo sed -i 's/#icon-theme-name=/icon-theme-name=Papirus-Dark/' /etc/lightdm/lightdm-gtk-greeter.conf
sudo sed -i 's/#font-name=/font-name=Ubuntu 12/' /etc/lightdm/lightdm-gtk-greeter.conf

CURSOR=(grep cursor-theme-name=capitaine /etc/lightdm/lightdm-gtk-greeter.conf)

if [ "CURSOR" != "cursor-theme-name=capitaine-cursors-light" ]

	then
	
		sudo awk 'BEGIN{printf "\ncursor-theme-name=capitaine-cursors-light" >> "/etc/lightdm/lightdm-gtk-greeter.conf"}'
	
fi
tput setaf 2
echo -e "\033[5m LightDM Customizations Set"
tput sgr0



#####Change cursor theme#####
xfconf-query --channel xsettings --property /Gtk/CursorThemeName --set capitaine-cursors-light
tput setaf 2
echo -e "\033[5m Cursor Theme Set"
tput sgr0



#####Install YAY#####
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin/
makepkg -si --noconfirm
tput setaf 2
echo -e "\033[5m YAY has been installed"
tput sgr0



#####Install AUR programs#####
func_install()
{
	if pacman -Qi $1 &> /dev/null

		then
		
			tput sgr0
			tput setaf 4
			echo ""$1" is installed"

		else
		
			tput sgr0
			yay -S --noconfirm --needed $1
			echo "Installing package" $1

	fi
}

list=(
		gtkhash-thunar
		inxi
		kvantum-theme-arc
		librewolf-bin
		timeshift
		timeshift-autosnap
     )

count=0

for name in "${list[@]}"

	do
		count=$[count+1]
		tput setaf 3
		echo -e "\033[7m Installing "$count":"$name;
		func_install $name
		
	done

tput setaf 2
echo -e "\033[5m Software has been installed"
tput sgr0



#####Change Timeshift max snapshots#####
sudo sed -i 's/3/10/' /etc/timeshift-autosnap.conf
tput setaf 2
echo -e "\033[5m Timeshift Max Snapshots Set To 10"
tput sgr0



#####Activate Reflector#####
sudo sed -i 's/# --country France,Germany/--country Romania/' /etc/xdg/reflector/reflector.conf
sudo sed -i 's/5/10/' /etc/xdg/reflector/reflector.conf
sudo sed -i 's/age/rate/' /etc/xdg/reflector/reflector.conf
sudo systemctl enable reflector.timer
tput setaf 2
echo -e "\033[5m Reflector Timer Set and Configured"
tput sgr0
