#!/bin/bash


#####Install CPU microcode#####
echo what cpu?
read cpu

if [ "$cpu" == "amd" ]

	then
	
		tput sgr0
		sudo pacman -S amd-ucode --noconfirm --needed
		tput setaf 2
		echo -e "\033[5m ${cpu} CPU microcode has been installed"
		tput sgr0
	
	elif [ "$cpu" == "intel" ]; then
	
		sudo pacman -S intel-ucode --noconfirm --needed
		tput setaf 2
		echo -e "\033[5m ${cpu} CPU microcode has been installed"
		tput sgr0
		
	else
	
		tput setaf 1
		echo -e "\033[5m CPU microcode has been NOT installed"
		tput sgr0
	
fi



#####Install GPU driver#####
echo what gpu?
read gpu

if [ "$gpu" == "amd" ]

	then
	
		sudo pacman -S mesa lib32-mesa vulkan-radeon lib32-vulkan-radeon libva-mesa-driver lib32-libva-mesa-driver mesa-vdpau lib32-mesa-vdpau libva-vdpau-driver lib32-libva-vdpau-driver libvdpau-va-gl --noconfirm --needed
		tput setaf 2
		echo -e "\033[5m ${gpu} GPU driver has been installed"
		tput sgr0
		
	else
	
		tput setaf 1
		echo -e "\033[5m GPU driver has been NOT installed"
		tput sgr0
fi



#####Uniformize GTK & QT look#####
QTSTYLE=(grep QT_STYLE_OVERRIDE /etc/environment)

if [ "QTSTYLE" != "QT_STYLE_OVERRIDE=kvantum" ]

	then
	
		sudo awk 'BEGIN{printf "\nQT_STYLE_OVERRIDE=kvantum" >> "/etc/environment"}'
	
fi



#####Add fcitx variables#####
GTK=(grep GTK_IM_MODULE /etc/environment)
QTMOD=(grep QT_IM_MODULE /etc/environment)
XMOD=(grep XMODIFIERS=@im /etc/environment)
    
if [ "GTK" != "GTK_IM_MODULE=fcitx" ]

	then
	
		sudo awk 'BEGIN{printf "\nGTK_IM_MODULE=fcitx" >> "/etc/environment"}'
	
fi

if [ "QTMOD" != "QT_IM_MODULE=fcitx" ]

	then
	
		sudo awk 'BEGIN{printf "\nQT_IM_MODULE=fcitx" >> "/etc/environment"}'
	
fi

if [ "XMOD" != "XMODIFIERS=@im=fcitx=fcitx" ]

	then
	
		sudo awk 'BEGIN{printf "\nXMODIFIERS=@im=fcitx" >> "/etc/environment"}'
	
fi



#####Edit pacman.conf#####
#COMMENT /s/^.// replaces character 1 "." with what's within the //, so it deletes it
sudo sed -i '/#Color/s/^.//' /etc/pacman.conf
sudo sed -i '/#VerbosePkgLists/s/^.//' /etc/pacman.conf
#COMMENT /s/\n/\n#/ replaces \n(ext line) with \n(ext something else)
sudo sed -i '/#ParallelDownloads = 5/!b;N;s/^.//;s/\n/\nILoveCandy/' /etc/pacman.conf
#COMMENT /s/^/#/ replaces character 0 with what's within the //, so it adds # to the beginning of the line
sudo sed -i '/\[multilib-testing\]/!b;N;s/^/#/;s/\n/\n#/' /etc/pacman.conf
sudo sed -i '/##\[multilib-testing\]/!b;N;s/^.//;s/\n##/\n#/' /etc/pacman.conf



#####Uninstall programs#####
func_install()
{
	if pacman -Qi $1 &> /dev/null

		then
		
			tput sgr0
			sudo pacman -Rn --noconfirm $1
			echo "Uninstalling package" $1

		else
		
			tput sgr0
			tput setaf 4
			echo ""$1" is not installed"

	fi
}

list=(
		htop
		parole
		ristretto
		vim
		vim-runtime
		xarchiver
		xfburn
		xfce4-sensors-plugin
		xfce4-taskmanager
	)

count=0

for name in "${list[@]}"

	do
	
		count=$[count+1]
		tput setaf 3
		echo -e "\033[7m Uninstalling "$count":"$name;
		func_install $name
		
	done

tput setaf 2
echo -e "\033[5m Software has been uninstalled"
tput sgr0



#####Install programs#####
func_install()
{
	if pacman -Qi $1 &> /dev/null

		then
		
			tput sgr0
			tput setaf 4
			echo ""$1" is installed"

		else
		
			tput sgr0
			sudo pacman -S --noconfirm --needed $1
			echo "Installing package" $1

	fi
}

list=(
		archlinux-wallpaper
		arc-gtk-theme
		btop
		capitaine-cursors
		evince
		fcitx5
		fcitx5-configtool
		fcitx5-gtk
		fcitx5-mozc
		fcitx5-qt
		ffmpeg
		file-roller
		git
		gnome-calculator
		gnome-disk-utility
		gnome-font-viewer
		gtk4
		gvfs-mtp
		kvantum
		libreoffice-fresh
		linux-headers
		lxtask
		mediainfo
		mesa-vdpau
		mpv
		ntfs-3g
		p7zip
		papirus-icon-theme
		qbittorrent
		ttf-ubuntu-font-family
		vdpauinfo
		viewnior
		yt-dlp
		zip
	)

count=0

for name in "${list[@]}"

	do
		count=$[count+1]
		tput setaf 3
		echo -e "\033[7m Installing "$count":"$name;
		func_install $name
		
	done

tput setaf 2
echo -e "\033[5m Software has been installed"
tput sgr0



#####Install YAY#####
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin/
makepkg -si --noconfirm
tput setaf 2
echo -e "\033[5m YAY has been installed"
tput sgr0



#####Install AUR programs#####
func_install()
{
	if pacman -Qi $1 &> /dev/null

		then
		
			tput sgr0
			tput setaf 4
			echo ""$1" is installed"

		else
		
			tput sgr0
			yay -S --noconfirm --needed $1
			echo "Installing package" $1

	fi
}

list=(
		breeze-snow-cursor-theme
		inxi
		kvantum-theme-arc
		librewolf-bin
		timeshift
		timeshift-autosnap
     )

count=0

for name in "${list[@]}"

	do
		count=$[count+1]
		tput setaf 3
		echo -e "\033[7m Installing "$count":"$name;
		func_install $name
		
	done

tput setaf 2
echo -e "\033[5m Software has been installed"
tput sgr0



#####Enable LightDM autologin######
sudo groupadd -r autologin
sudo gpasswd -a $USER autologin
sudo sed -i "s/#autologin-user=/autologin-user=$USER/" /etc/lightdm/lightdm.conf



#####Customize LightDM#####
sudo sed -i 's/#background=/background=\/usr\/share\/backgrounds\/archlinux\/awesome.png/' /etc/lightdm/lightdm-gtk-greeter.conf
sudo sed -i 's/#theme-name=/theme-name=Arc-Dark/' /etc/lightdm/lightdm-gtk-greeter.conf
sudo sed -i 's/#icon-theme-name=/icon-theme-name=Papirus-Dark/' /etc/lightdm/lightdm-gtk-greeter.conf
sudo sed -i 's/#font-name=/font-name=Ubuntu 12/' /etc/lightdm/lightdm-gtk-greeter.conf

CURSOR=(grep cursor-theme-name=capitaine /etc/lightdm/lightdm-gtk-greeter.conf)

if [ "CURSOR" != "cursor-theme-name=capitaine-cursors-light" ]

	then
	
		sudo awk 'BEGIN{printf "\ncursor-theme-name=capitaine-cursors-light" >> "/etc/lightdm/lightdm-gtk-greeter.conf"}'
	
fi



#####Change cursor theme#####
xfconf-query --channel xsettings --property /Gtk/CursorThemeName --set capitaine-cursors-light
